CREATE EXTENSION IF NOT EXISTS "UUID-OSSP";

CREATE TYPE BODYTYPE AS ENUM ('ECTOMORPH','ENDOMORPH','MESOMORPH');
CREATE TYPE OBJECTIVE AS ENUM ('GAIN', 'LOSE');
CREATE TYPE EATINGHABITS AS ENUM ('JUNK FOOD', 'HEALTH FOOD');

CREATE TABLE IF NOT EXISTS USERS (
ID UUID NOT NULL PRIMARY KEY DEFAULT UUID_GENERATE_V4(),
USERNAME VARCHAR(100) NOT NULL,
PASSWORD VARCHAR(100) NOT NULL,
EMAIL VARCHAR(255) UNIQUE NOT NULL,
CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
ID_HEALTH_ANALYSIS UUID UNIQUE,
ID_PROPOSED_DIET UUID UNIQUE);

CREATE TABLE IF NOT EXISTS HEALTH_ANALYSIS ( ID UUID NOT NULL PRIMARY KEY DEFAULT UUID_GENERATE_V4(),
GENRE CHAR(1) NOT NULL,
HEIGHT VARCHAR(10) NOT NULL,
WEIGHT VARCHAR(10) NOT NULL,
BIRTHDATE VARCHAR(11) NOT NULL,
BODYTYPE BODYTYPE NOT NULL,
OBJECTIVE OBJECTIVE NOT NULL,
EXERCISETIME NUMERIC(4, 2) NOT NULL,
CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
ID_USER UUID UNIQUE );

CREATE TABLE IF NOT EXISTS PROPOSED_DIET ( ID UUID NOT NULL PRIMARY KEY DEFAULT UUID_GENERATE_V4(),
ID_USER UUID UNIQUE,
CALORIES VARCHAR(10) NOT NULL,
CARBOHYDRATES VARCHAR(10) NOT NULL,
PROTEIN VARCHAR(10) NOT NULL,
LIPIDS VARCHAR(10) NOT NULL,
WATER VARCHAR(10) NOT NULL,
MEALS VARCHAR(10) NOT NULL);

ALTER TABLE USERS
ADD CONSTRAINT FK_ID_HEALTH_ANALYSIS FOREIGN KEY (ID_HEALTH_ANALYSIS) REFERENCES HEALTH_ANALYSIS(ID);

ALTER TABLE USERS
ADD CONSTRAINT FK_ID_PROPOSED_DIET FOREIGN KEY (ID_PROPOSED_DIET) REFERENCES PROPOSED_DIET(ID);

CREATE TABLE IF NOT EXISTS PARAMETERS (
NAME VARCHAR(200) NOT NULL,
"key" VARCHAR(200) NOT NULL,
VALUE VARCHAR(10000),
CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
constraint parameters_pk primary key (NAME, "key")
);

