CREATE EXTENSION IF NOT EXISTS "UUID-OSSP";
CREATE TYPE BODYTYPE AS ENUM ('ECTOMORPH', 'ENDOMORPH', 'MESOMORPH');
CREATE TYPE LIFESTYLE AS ENUM ('SEDENTARY', 'CASUAL', 'ATHLETE');
CREATE TYPE EATINGHABITS AS ENUM ('JUNK FOOD', 'HEALTH FOOD');
CREATE TABLE IF NOT EXISTS USERS (
  ID UUID NOT NULL PRIMARY KEY DEFAULT UUID_GENERATE_V4(),
  USERNAME VARCHAR(100) NOT NULL,
  PASSWORD VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(255) UNIQUE NOT NULL,
  BIRTHDATE VARCHAR(11) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
  LAST_LOGIN TIMESTAMP NOT NULL,
  ID_HEALTH_ANALYSIS UUID UNIQUE,
  ID_PROPOSED_DIET UUID UNIQUE
);
CREATE TABLE IF NOT EXISTS HEALTH_ANALYSIS (
  ID UUID NOT NULL PRIMARY KEY DEFAULT UUID_GENERATE_V4(),
  GENRE CHAR(1) NOT NULL,
  HEIGHT VARCHAR(10) NOT NULL,
  WEIGHT VARCHAR(10) NOT NULL,
  BODYTYPE BODYTYPE NOT NULL,
  LIFESTYLE LIFESTYLE NOT NULL,
  FATAMOUNT VARCHAR(10) NOT NULL,
  MUSCLEMASS VARCHAR(10) NOT NULL,
  EATINGHABITS EATINGHABITS NOT NULL CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
  ID_USER UUID UNIQUE
);
CREATE TABLE PROPOSED_DIET (
  ID UUID NOT NULL PRIMARY KEY DEFAULT UUID_GENERATE_V4(),
  CALORIES_AMOUNT VARCHAR(10) NOT NULL,
  CARBOHYDRATES_AMOUNT VARCHAR(10) NOT NULL,
  PROTEIN_AMOUNT VARCHAR(10) NOT NULL,
  LIPIDS_AMOUNT VARCHAR(10) NOT NULL,
  WATER_AMOUNT VARCHAR(10) NOT NULL,
  MEALS_AMOUNT VARCHAR(10) NOT NULL,
  ID_USER UUID UNIQUE
);
ALTER TABLE USERS
ADD CONSTRAINT FK_ID_HEALTH_ANALYSIS FOREIGN KEY (ID_HEALTH_ANALYSIS) REFERENCES HEALTH_ANALYSIS(ID);
ALTER TABLE USERS
ADD CONSTRAINT FK_ID_PROPOSED_DIET FOREIGN KEY (ID_PROPOSED_DIET) REFERENCES PROPOSED_DIET(ID);
ALTER TABLE HEALTH_ANALYSIS
ADD CONSTRAINT FK_ID_USER FOREIGN KEY (ID_USER) REFERENCES USERS(ID);
ALTER TABLE PROPOSED_DIET
ADD CONSTRAINT FK_ID_USER FOREIGN KEY (ID_USER) REFERENCES USERS(ID);
CREATE TABLE IF NOT EXISTS PARAMETERS (
  NAME VARCHAR(200) NOT NULL,
  "key" VARCHAR(200) NOT NULL,
  VALUE VARCHAR(10000),
  CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
  constraint parameters_pk primary key (NAME, "key")
);
