openapi: 3.0.0
info:
  title: Nutrieasy Server API
  description: Here you can find all resources to work with the Nutrieasy API.
  version: 0.1.9
servers:
  - url: http://localhost:3080/nutrieasy
    description: Localhost server, e.g. Main (local) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing

# 1) Define the security scheme type (HTTP bearer)
components:
  securitySchemes:
    basicAuth: # <-- arbitrary name for the security scheme
      type: http
      scheme: basic
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT # optional, arbitrary value for documentation purposes

paths:
  /auth/login:
    post:
      tags:
        - Authentication
      security:
        - basicAuth: [] # <-- use the same name here
      summary: Login into application.
      responses:
        '201':
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  user:
                    type: string
        '401':
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
        '500':
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string

  /auth/signup:
    post:
      tags:
        - Authentication
      # security:
      #   - bearerAuth: []
      summary: Register an user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                username:
                  type: string
                password:
                  type: string
      responses:
        '201':
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  user:
                    type: string
        '401':
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
        '500':
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string

  /users/{userid}:
    get:
      tags:
        - Users
      # security:
      #   - bearerAuth: []
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      parameters:
        - name: userId
          in: path
          required: true
          description: Parameter description in CommonMark or HTML.
      responses:
        '200': # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
